services:
  frontend:
    container_name: blog-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - my-vol:/app/node_modules/
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    container_name: blog-backend
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - my-vol:/app/node_modules/
    env_file:
      - .env
    depends_on:
      - postgres
      - mailhog

  postgres:
    image: postgres:15
    container_name: blog-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-blog_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: blog-pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@blog.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog
    container_name: blog-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

volumes:
  my-vol:
    driver: local
  pgdata:
